# Generated by Django 2.0.5 on 2018-09-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_service', models.CharField(db_index=True, max_length=30)),
                ('type', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=40)),
                ('amount', models.IntegerField(default=0)),
                ('action', models.CharField(db_index=True, max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('increment_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
